# Generated by Django 5.2.6 on 2025-09-30 01:06

from django.db import migrations, models
import datetime # <--- NOVO IMPORT NECESSÁRIO AQUI!

class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='desempenho',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='senha',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(default='Não informada', max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf_responsavel',
            # CORRIGIDO: Default string mais robusta
            field=models.CharField(default='000.000.000-00', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            # CORRIGIDO: Usando objeto datetime.date válido para a migração
            field=models.DateField(default=datetime.date(2000, 1, 1)), 
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_responsavel',
            # CORRIGIDO: Default string mais robusta
            field=models.CharField(default='Não Informado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero_responsavel',
            # CORRIGIDO: Default string mais robusta
            field=models.CharField(default='(00) 00000-0000', max_length=15),
            preserve_default=False,
        ),
    ]