# Generated by Django 5.2.6 on 2025-09-30 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_remove_aluno_desempenho_remove_aluno_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf_responsavel',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(default='Endereço Não Informado', max_length=200),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='Aluno Novo', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_responsavel',
            field=models.CharField(default='Responsável Não Informado', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero_responsavel',
            field=models.CharField(default='(00) 00000-0000', max_length=15),
        ),
    ]
