# Generated by Django 5.2.6 on 2025-09-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_aluno_bairro_alter_aluno_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
