# Generated by Django 5.2.6 on 2025-09-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_alter_aluno_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf_responsavel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero_responsavel',
            field=models.CharField(max_length=11),
        ),
    ]
