# Generated by Django 5.2.6 on 2025-09-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('instrutor', 'Instrutor'), ('recepcao', 'Recepção'), ('administracao', 'Administração')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('idade', models.PositiveIntegerField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
    ]
