# Generated by Django 5.2.6 on 2025-09-09 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=20)),
                ('quantidade_alunos', models.PositiveIntegerField(default=0)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'cargo': 'instrutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='funcionarios.funcionario')),
            ],
        ),
    ]
